name: CARD
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - r::r-base
  - r::r-irkernel
  - r-matrix
  - r-devtools
  - r-mass
  - r::r-units
  - conda-forge::r-systemfonts
  - conda-forge::r-s2
  - conda-forge::r-v8
  - conda-forge::r-sf
  - r::r-concaveman
  - r::r-viridis
  - anaconda::fonts-anaconda
prefix: /opt/conda/envs/CARD