name: EnDecon
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://conda.anaconda.org/conda-forge
dependencies:
  - r-base=4.4.3
  - r-mass
  - r-systemfonts=1.2.1
  - r-viridis=0.6.5
  - fonts-anaconda
  - r-devtools
  - r-matrix
  - r-s2
  - r-units=1.0_0
  - r-irkernel=1.3.2
  - r-concaveman=1.2.0
  - r-sf=1.0_21
  - r-v8=8.0.1
  - r-clusterr
  - r-magick
  - r-ggpubr
  - r-spatstat.geom
  - r-spatstat
prefix: /opt/conda/envs/EnDecon
